import type { Metadata } from "next";
import { Inter as InterFont, Archivo as ArchivoFont } from "next/font/google";
import "./globals.css";

const inter = InterFont({ subsets: ["latin"] });
const archivo = ArchivoFont({
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${archivo.className}} antialiased`}>
        {children}
      </body>
    </html>
  );
}
